import { HashMap } from './hashmap.js';
import { HashSet } from './hashset.js';

// HashMap showcase:
const hashmap = new HashMap();
console.log(hashmap);
console.log(`Number of Buckets: ${hashmap.buckets.length}`);
console.log(hashmap.entries(), '\n');
hashmap.set('apple', 'red');
hashmap.set('banana', 'yellow');
hashmap.set('carrot', 'orange');
hashmap.set('dog', 'brown');
hashmap.set('elephant', 'gray');
hashmap.set('frog', 'green');
hashmap.set('grape', 'purple');
hashmap.set('hat', 'black');
hashmap.set('ice cream', 'white');
hashmap.set('jacket', 'blue');
hashmap.set('kite', 'pink');
hashmap.set('lion', 'golden');
hashmap.set('lion', 'golden');
hashmap.set('lion', 'golden');
console.log(hashmap);
console.log(`Number of Buckets: ${hashmap.buckets.length}`);
console.log(hashmap.entries(), '\n');
hashmap.set('diamond', 'aquamarine');
hashmap.set('butterfly', 'rebeccapurple');
hashmap.set('grass', 'greenyellow');
hashmap.set('dog', 'tan');
hashmap.set('jacket', 'navy');
console.log(hashmap);
console.log(`Number of Buckets: ${hashmap.buckets.length}`);
console.log(hashmap.entries(), '\n');
console.log(`lion: ${hashmap.get('lion')}`);
console.log(`dog: ${hashmap.get('dog')}`);
console.log(`hashmap: ${hashmap.get('hashmap')}`);
console.log(`jacket: ${hashmap.get('jacket')}`, '\n');
console.log(`Removed hashmap: ${hashmap.remove('hashmap')}`);
console.log(`Removed jacket: ${hashmap.remove('jacket')}`);
console.log(`Has hashmap: ${hashmap.has('hashmap')}`);
console.log(`Has jacket: ${hashmap.has('jacket')}`, '\n');
console.log(`HashMap Keys: ${hashmap.keys()}`);
console.log(`HashMap Values: ${hashmap.values()}`);
console.log(`HashMap Size: ${hashmap.length()}`, '\n');
console.log('HashMap Cleared!');
hashmap.clear();
console.log(hashmap);
console.log(`Number of Buckets: ${hashmap.buckets.length}`);
console.log(hashmap.entries(), '\n');
console.log('HashMap Finishes Here!\n');

// HashSet showcase:
const hashset = new HashSet();
console.log('HashSet Starts Here!\n');
console.log(hashset);
console.log(`Number of Buckets: ${hashset.buckets.length}`);
console.log(hashset.entries(), '\n');
hashset.set('red');
hashset.set('yellow');
hashset.set('orange');
hashset.set('brown');
hashset.set('gray');
hashset.set('green');
hashset.set('purple');
hashset.set('black');
hashset.set('white');
hashset.set('blue');
hashset.set('pink');
hashset.set('golden');
hashset.set('golden');
hashset.set('golden');
console.log(hashset);
console.log(hashset.entries(), '\n');
hashset.set('aquamarine');
hashset.set('rebeccapurple');
hashset.set('greenyellow');
console.log(hashset);
console.log(`Number of Buckets: ${hashset.buckets.length}`);
console.log(hashset.entries(), '\n');
console.log(`HashSet Size: ${hashset.length()}`, '\n');
console.log(`Removed Green: ${hashset.remove('green')}`);
console.log(`Removed Green: ${hashset.remove('green')}`);
console.log(`Removed Brown: ${hashset.remove('brown')}`);
console.log(`Removed Brown: ${hashset.remove('brown')}`, '\n');
console.log(`Has Green: ${hashset.has('green')}`);
console.log(`Has Brown: ${hashset.has('brown')}`);
console.log(`Has Blue: ${hashset.has('blue')}`, '\n');
hashset.clear();
console.log('HashSet Cleared!');
console.log(hashset);
console.log(`Number of Buckets: ${hashset.buckets.length}`);
console.log(hashset.entries());
